version: '3.8'

services:
  # DATABASE
  mysqldb:
    image: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_MYSQL_PASSWORD
      - MYSQL_DATABASE=$DB_MYSQL_DATABASE
    ports:
      - $DB_MYSQL_LOCAL_PORT:$DB_MYSQL_DOCKER_PORT
  # NODE_PROJECT
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
